Repository Laravel-Backpack/Generators, pull requests merged in 2022-09, with the labels that each got.

#140 Command to create a new page
  src/Console/Commands/PageBackpackCommand.php
  src/Console/Commands/PageControllerBackpackCommand.php
  src/Console/stubs/page-controller.stub
  src/Console/stubs/page.stub
  src/GeneratorsServiceProvider.php
Labels: Priority: MUST

#142 Converted namespaces into file links on backpack:crud command
  src/Console/Commands/CrudControllerBackpackCommand.php
  src/Console/Commands/CrudModelBackpackCommand.php
  src/Console/Commands/CrudRequestBackpackCommand.php
Labels: enhancement, Priority: SHOULD

#141 Create a php artisan backpack:button command
  README.md
  src/Console/Commands/ButtonBackpackCommand.php
  src/Console/stubs/button.stub
  src/GeneratorsServiceProvider.php
Labels: Priority: SHOULD, Feature

#147 Default validation as request for the backpack:crud command
  src/Console/Commands/BuildBackpackCommand.php
Labels: bug

#144 php artisan backpack:field command
  src/Console/Commands/FieldBackpackCommand.php
  src/Console/stubs/field.stub
  src/Console/stubs/with-assets.stub
Labels: Priority: SHOULD

#145 Fixed CRUD Controller generated fields and columns
  src/Console/Commands/CrudControllerBackpackCommand.php
Labels: bug, Priority: MUST

#149 remove l8 breaking code
  src/Console/Commands/CrudModelBackpackCommand.php
  src/Console/Commands/PageControllerBackpackCommand.php
Labels: bug, Priority: MUST

#133 use the camelcased version of operation name
  src/Console/Commands/CrudOperationBackpackCommand.php
  src/Console/stubs/crud-operation.stub
Labels: Priority: COULD, Priority: SHOULD, Minor Bug

#152 Artisan command to generate new columns
  src/Console/Commands/ColumnBackpackCommand.php
  src/Console/stubs/column.stub
  src/GeneratorsServiceProvider.php
Labels: Priority: MUST
