Repository Laravel-Backpack/Generators, pull requests merged in 2023-07, with the labels that each got.

#189 v6
  README.md
  composer.json
  src/Console/Commands/CrudBackpackCommand.php
  src/Console/Commands/CrudFormOperationBackpackCommand.php
  src/Console/Commands/CrudModelBackpackCommand.php
  src/Console/Commands/PageBackpackCommand.php
  src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php
  src/Console/Commands/Views/WidgetBackpackCommand.php
  src/Console/stubs/crud-form-operation.stub
  src/GeneratorsServiceProvider.php
Labels: Priority: MUST

#198 dont use Str value() function unavailable in Laravel 8
  src/Console/Commands/BuildBackpackCommand.php
Labels: bug

#199 update stubs - remove $dates property, use basset, remove array syntax
  src/Console/stubs/crud-controller.stub
  src/Console/stubs/crud-model.stub
  src/Console/stubs/field.stub
  src/Console/stubs/filter.stub
  src/Console/stubs/model-softdelete.stub
  src/Console/stubs/model.stub
Labels: Priority: SHOULD, Minor Bug

#197 Pr/188 - allow stub publish
  src/Console/Commands/ChartControllerBackpackCommand.php
  src/Console/Commands/ConfigBackpackCommand.php
  src/Console/Commands/CrudControllerBackpackCommand.php
  src/Console/Commands/CrudModelBackpackCommand.php
  src/Console/Commands/CrudOperationBackpackCommand.php
  src/Console/Commands/CrudRequestBackpackCommand.php
  src/Console/Commands/ModelBackpackCommand.php
  src/Console/Commands/PageBackpackCommand.php
  src/Console/Commands/PageControllerBackpackCommand.php
  src/Console/Commands/RequestBackpackCommand.php
  src/Console/Commands/Traits/PublishableStubTrait.php
  src/Console/Commands/ViewBackpackCommand.php
  src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php
  src/GeneratorsServiceProvider.php
Labels: Priority: COULD, Priority: SHOULD, Size: XS
