Repository Laravel-Backpack/Generators, pull requests merged in 2023-01, with the labels that each got.

#130 Fix location for where model is generated
  src/Console/Commands/ModelBackpackCommand.php
Labels: Priority: SHOULD

#119 Models should have a `HasFactory` trait
  src/Console/stubs/crud-model.stub
Labels: enhancement, Priority: SHOULD

#174 hotfix
  src/Services/BackpackCommand.php
Labels: needs-more-info
